export {
  buildTgAuthDeeplink,
  connectMongo,
  getEnv,
  isBotConfigured,
  isGoogleOAuthConfigured,
  sendBotMessage,
  signToken,
  signTgLinkToken,
  TG_LINK_TTL_SECONDS,
  User,
  verifyTelegramInitData,
  verifyToken,
  verifyTgLinkToken,
  type SendBotMessageInput,
  type SendBotMessageResult,
  type TelegramInitData,
  type TelegramInitDataUser,
  type TgLinkTokenData,
  type UserDoc,
  type UserModel,
  type WaveEnv,
} from "@wave/shared";
export {
  pickLang,
  pickWebLang,
  SUPPORTED_WEB_LANGS,
  t,
  type I18nKey,
  type Lang,
} from "./i18n";
